[ColorThemes]
Max_slot=0

[CueBuss1]
name=""
reatype=3
send_to_masterparent=0
show_routing=1
solo_defeat=1
track_template_enabled=0
track_template_path=""

[Cyclactions]
PreventUIRefresh=1
Undos=1

[FXChains]
Max_slot=0

[General]
; /home/ariel/.config/REAPER/S&M.ini ===
; REAPER v7.20/linux-x86_64 ===
; SWS/S&M Extension v2.14.0 Build 7 ===
Beta=0
BuggyPlugsSupport=0
ExtensionsSubmenu=1
IniFileUpgrade=9
LearnPitchAndNormOSC=0
MediaFileLockAudio=0
ToolbarsAutoRefresh=1
ToolbarsAutoRefreshFreq=300 ; in ms (min: 100, max: 5000)

[ImageView]
Stretch=0

[LiveConfigs]
BigFontName=Arial

[MediaFiles]
Max_slot=0

[Misc]
RemoveAllEnvsSelTracksPrompt=1

[NbOfActions]
; Set the number of actions you want below. Quit REAPER first! ===
; Unless specified, the maximum number of actions is 255 (0 will hide actions). ===
S&M_ADD_TRTEMPLATE=4                     ; [Principal] Recursos: Importar pistas from Plantilla de pista, casilla n
S&M_ADDMEDIA_CURTRACK=4                  ; [Principal] Recursos: Añadir archivo to current pista, casilla n
S&M_ADDMEDIA_NEWTRACK=4                  ; [Principal] Recursos: Añadir archivo to new pista, casilla n
S&M_ADDMEDIA_SELITEM=4                   ; [Principal] Recursos: Añadir archivo a los items Seleccionados as takes, casilla n
S&M_APPLY_PRJTEMPLATE=4                  ; [Principal] Recursos: Abrir proyecto, casilla n
S&M_APPLY_TRTEMPLATE=4                   ; [Principal] Recursos: Apply Plantilla de pista a las pistas seleccionadas, casilla n
S&M_APPLY_TRTEMPLATE_ITEMSENVS=4         ; [Principal] Recursos: Apply Plantilla de pista (+envelopes/Items) a las pistas seleccionadas, casilla n
S&M_CLR_IMAGE_SLOT=0                     ; [Principal] Recursos: Reiniciar casilla de Imagen n
S&M_CLR_MEDIA_SLOT=0                     ; [Principal] Recursos: Reiniciar casilla de archivo n
S&M_CLR_PRJTEMPLATE_SLOT=0               ; [Principal] Recursos: Reiniciar casilla de proyecto n
S&M_CLR_THEME_SLOT=0                     ; [Principal] Recursos: Reiniciar casilla de Tema n
S&M_CLR_TRTEMPLATE_SLOT=0                ; [Principal] Recursos: Reiniciar casilla de Plantilla de pista n
S&M_CLRFXCHAINSLOT=0                     ; [Principal] Recursos: Reiniciar casilla de Cadena de FX n
S&M_CUEBUS=8                             ; [Principal] Crear un Bus para las pistas seleccionadas, Ajuste n -- Max. = 8!
S&M_DUMMY_TGL=8                          ; [Principal] Dummy (Activar/Desactivar) n 
S&M_EXCL_TGL=4                           ; [Principal] Exclusive (Activar/Desactivar) LAn
S&M_EXCL_TGL_B=4                         ; [Principal] Exclusive (Activar/Desactivar) SIn
S&M_EXCL_TGL_C=4                         ; [Principal] Exclusive (Activar/Desactivar) DOn
S&M_EXCL_TGL_D=4                         ; [Principal] Exclusive (Activar/Desactivar) REn
S&M_EXCL_TGL_E=0                         ; [Principal] Exclusive (Activar/Desactivar) MIn
S&M_EXCL_TGL_F=0                         ; [Principal] Exclusive (Activar/Desactivar) FAn
S&M_EXCL_TGL_G=0                         ; [Principal] Exclusive (Activar/Desactivar) SOLn
S&M_EXCL_TGL_H=0                         ; [Principal] Exclusive (Activar/Desactivar) Hn
S&M_FLOATFX=8                            ; [Principal] Abrir FX n en Ventana Flotante para las pistas seleccionadas
S&M_FXBYP=8                              ; [Principal] Activar/Desactivar FX n En las pistas seleccionadas
S&M_FXBYP_ALL_OFF_EXCPT=0                ; [Principal] Activar Todos los FX (Excepto el n) En las pistas seleccionadas
S&M_FXBYP_ALL_ON_EXCPT=8                 ; [Principal] Desactivar Todos los FX (Excepto el n) En las pistas seleccionadas
S&M_FXBYP_SETOFF=8                       ; [Principal] Activar FX n En las pistas seleccionadas
S&M_FXBYP_SETON=8                        ; [Principal] Desactivar FX n En las pistas seleccionadas
S&M_FXBYPEXCPT=0                         ; [Principal] Activar/Desactivar Todos los FX (Excepto el n) En las pistas seleccionadas
S&M_FXCHAIN_ALLTAKES=0                   ; [Principal] Recursos: Pegar (Reemplazar) Cadena de FX en los items Seleccionados, Todas las tomas, casilla n
S&M_FXOFF=8                              ; [Principal] Apagar / Encender el FX n en las pistas seleccionadas
S&M_FXOFF_ALL_OFF_EXCPT=8                ; [Principal] Apagar Todos los FX (Excepto el n) En las pistas seleccionadas
S&M_FXOFF_ALL_ON_EXCPT=0                 ; [Principal] Encender Todos los FX (Excepto el n) En las pistas seleccionadas
S&M_FXOFF_SETOFF=8                       ; [Principal] Apagar FX n En las pistas seleccionadas
S&M_FXOFF_SETON=8                        ; [Principal] Encender FX n En las pistas seleccionadas
S&M_FXOFFEXCPT=0                         ; [Principal] Encender de Todos los FX (Excepto el n) En las pistas seleccionadas (Activar/Desactivar)
S&M_GOTO_MARKER=0                        ; [Principal] Ir al marcador n (Respetar Opción de Seguimiento Suave)
S&M_GOTO_REGION=0                        ; [Principal] Ir a la región n (Respetar Opción de Seguimiento Suave)
S&M_GOTO_SEL_REGION=4                    ; [Principal] Go to/time-select region n (obeys smooth seek)
S&M_INFXCHAIN=0                          ; [Principal] Recursos: Pegar (Reemplazar) Cadena de FX de entrada a las pistas seleccionadas, casilla n
S&M_LIVECFG_APPLY=8                      ; [Principal] Live Config #n - Apply config (Sólo MIDI CC/OSC) -- Max. = 8!
S&M_LIVECFG_CC123_OFF=0                  ; [Principal] Live Config #n - Desactivar Opción 'Send Todas las notas off when switching configs' -- Max. = 8!
S&M_LIVECFG_CC123_ON=0                   ; [Principal] Live Config #n - Activar Opción 'Send Todas las notas off when switching configs' -- Max. = 8!
S&M_LIVECFG_CC123_TGL=8                  ; [Principal] Live Config #n - Opción 'Send Todas las notas off when switching configs' (Activar/Desactivar) -- Max. = 8!
S&M_LIVECFG_DISARMBUT_OFF=0              ; [Principal] Live Config #n - Desactivar Opción 'Disarm all Excepto active pista' -- Max. = 8!
S&M_LIVECFG_DISARMBUT_ON=0               ; [Principal] Live Config #n - Activar Opción 'Disarm all Excepto active pista' -- Max. = 8!
S&M_LIVECFG_DISARMBUT_TGL=8              ; [Principal] Live Config #n - Opción 'Disarm all Excepto active pista' (Activar/Desactivar) -- Max. = 8!
S&M_LIVECFG_FADES_OFF=0                  ; [Principal] Live Config #n - Desactivar tiny Fades -- Max. = 8!
S&M_LIVECFG_FADES_ON=0                   ; [Principal] Live Config #n - Activar tiny Fades -- Max. = 8!
S&M_LIVECFG_FADES_TGL=8                  ; [Principal] Live Config #n - Activar tiny Fades (Activar/Desactivar) -- Max. = 8!
S&M_LIVECFG_MUTEBUT_OFF=0                ; [Principal] Live Config #n - Desactivar Opción 'Mute all Excepto active pista' -- Max. = 8!
S&M_LIVECFG_MUTEBUT_ON=0                 ; [Principal] Live Config #n - Activar Opción 'Mute all Excepto active pista' -- Max. = 8!
S&M_LIVECFG_MUTEBUT_TGL=8                ; [Principal] Live Config #n - Opción 'Mute all Excepto active pista' (Activar/Desactivar) -- Max. = 8!
S&M_LIVECFG_OFF=0                        ; [Principal] Live Config #n - Desactivar -- Max. = 8!
S&M_LIVECFG_OFFLINEBUT_OFF=0             ; [Principal] Live Config #n - Desactivar Opción 'Offline all Excepto active/preloaded pistas' -- Max. = 8!
S&M_LIVECFG_OFFLINEBUT_ON=0              ; [Principal] Live Config #n - Activar Opción 'Offline all Excepto active/preloaded pistas' -- Max. = 8!
S&M_LIVECFG_OFFLINEBUT_TGL=8             ; [Principal] Live Config #n - Opción 'Offline all Excepto active/preloaded pistas' (Activar/Desactivar) -- Max. = 8!
S&M_LIVECFG_ON=0                         ; [Principal] Live Config #n - Desactivar -- Max. = 8!
S&M_LIVECFG_PRELOAD=8                    ; [Principal] Live Config #n - Preload config (Sólo MIDI CC/OSC) -- Max. = 8!
S&M_LIVECFG_TGL=8                        ; [Principal] Live Config #n - Activar (Activar/Desactivar) -- Max. = 8!
S&M_LOAD_THEME=4                         ; [Principal] Recursos: Cargar Tema, casilla n
S&M_LOOPMEDIA_SELTRACK=4                 ; [Principal] Recursos: Loopear Items en las pistas seleccionadas, casilla n
S&M_LOOPMEDIA_SELTRACK_SYNC=4            ; [Principal] Recursos: Loop Items en las pistas seleccionadas (Al Comenzar el siguiente compás), casilla n
S&M_MAP_MIDI_INPUT_CH=16                 ; [Principal] Redirigir la Entrada MIDI de las pistas seleccionadas al canal n -- Max. = 16!
S&M_MESAVECCLANES=8                      ; [Principal] Active MIDI Editor - Guardar Capas de CC Desplegadas, casilla n
S&M_MESETCCLANES=8                       ; [Principal] Active MIDI Editor - Restaurar Capas de CC Desplegadas, casilla n
S&M_MIDI_INPUT_CH=16                     ; [Principal] Ajustar la Entrada MIDI de las pistas seleccionadas al canal n -- Max. = 16!
S&M_NEWTAB_PRJTEMPLATE=4                 ; [Principal] Recursos: Abrir proyecto, casilla n (Pestaña nueva)
S&M_NEXT_LIVE_CFG=8                      ; [Principal] Live Config #n - Aplicar la siguiente Configuración -- Max. = 8!
S&M_NEXT_PRESET_FX=4                     ; [Principal] Cargar el siguiente Preset del FX n en las pistas seleccionadas
S&M_OPEN_LIVECFG_MONITOR=8               ; [Principal] Live Config #n - Abrir/Cerrar monitoring window -- Max. = 8!
S&M_PASTE_FXCHAIN_ALLTAKES=0             ; [Principal] Recursos: Pegar Cadena de FX en los items Seleccionados, Todas las tomas, casilla n
S&M_PASTE_INFXCHAIN=0                    ; [Principal] Recursos: Pegar Cadena de FX de entrada a las pistas seleccionadas, casilla n
S&M_PASTE_TAKEFXCHAIN=4                  ; [Principal] Recursos: Pegar Cadena de FX en los items Seleccionados, casilla n
S&M_PASTE_TEMPLATE_ITEMS=4               ; [Principal] Recursos: Pegar Plantilla de items a las pistas seleccionadas, casilla n
S&M_PASTE_TRACKFXCHAIN=4                 ; [Principal] Recursos: Pegar Cadena de FX a las pistas seleccionadas, casilla n
S&M_PLAY_RGN_PLAYLIST=4                  ; [Principal] Lista de reproducción de regiones #n – Reproducir
S&M_PLAYMEDIA_SELTRACK=4                 ; [Principal] Recursos: Reproducir Items en las pistas seleccionadas, casilla n
S&M_PLAYMEDIA_SELTRACK_SYNC=4            ; [Principal] Recursos: Reproducir Items en las pistas seleccionadas (Al Comenzar el siguiente compás), casilla n
S&M_PRELOAD_LIVE_CFG=8                   ; [Principal] Live Config #n - Apply preloaded config (swap preload/current) -- Max. = 8!
S&M_PRELOAD_NEXT_LIVE_CFG=8              ; [Principal] Live Config #n - Preload next config -- Max. = 8!
S&M_PRELOAD_PREVIOUS_LIVE_CFG=8          ; [Principal] Live Config #n - Preload previous config -- Max. = 8!
S&M_PRESET_FX=8                          ; [Principal] Cargar el Preset del FX n en las pistas Seleccionada (Sólo MIDI CC/OSC) -- Max. = 8!
S&M_PREVIOUS_LIVE_CFG=8                  ; [Principal] Live Config #n - Aplicar la Configuración anterior -- Max. = 8!
S&M_PREVIOUS_PRESET_FX=4                 ; [Principal] Cargar el Preset anterior del FX n en las pistas seleccionadas
S&M_REPLACE_TEMPLATE_ITEMS=4             ; [Principal] Recursos: Pegar (Reemplazar) Plantilla de items a las pistas seleccionadas, casilla n
S&M_SAVECCLANES_ME=8                     ; [Editor MIDI] Guardar Capas de CC Desplegadas, casilla n
S&M_SELFX=8                              ; [Principal] Seleccionar FX n En las pistas seleccionadas
S&M_SET_TRACK_GROUP=8                    ; [Principal] Incluir las pistas seleccionadas en el grupo n (Etiquetar Por defecto) -- Max. = 64!
S&M_SET_TRACK_ICON=4                     ; [Principal] Recursos: Set Icono de pista En las pistas seleccionadas, casilla n
S&M_SETCCLANES_ME=8                      ; [Editor MIDI] Restaurar Capas de CC Desplegadas, casilla n
S&M_SHOW_IMG=4                           ; [Principal] Recursos: Mostrar Imagen, casilla n
S&M_SHOWFXCHAIN=8                        ; [Principal] Abrir Cadena de FX de las pistas seleccionadas, FX n
S&M_TAKEFXCHAIN=4                        ; [Principal] Recursos: Pegar (Reemplazar) Cadena de FX en los items Seleccionados, casilla n
S&M_TGL_LOOPMEDIA_SELTRACK=4             ; [Principal] Recursos: Loop Items en las pistas seleccionadas  (Activar/Desactivar), casilla n
S&M_TGL_PLAYMEDIA_SELTRACK=4             ; [Principal] Recursos: Reproducir Items en las pistas seleccionadas (Activar/Desactivar), casilla n
S&M_TGLPAUSE_LOOPMEDIA_SELTR=0           ; [Principal] Recursos: Loop Items en las pistas seleccionadas (Activar/Desactivar la pausa), casilla n
S&M_TGLPAUSE_PLAYMEDIA_SELTR=4           ; [Principal] Recursos: Reproducir Items en las pistas seleccionadas (Activar/Desactivar la pausa), casilla n
S&M_TOGLFLOATFX=8                        ; [Principal] Abrir FX n en Ventana Flotante para las pistas seleccionadas (Activar/Desactivar)
S&M_TRACKFXCHAIN=4                       ; [Principal] Recursos: Pegar (Reemplazar) Cadena de FX a las pistas seleccionadas, casilla n
S&M_UNFLOATFX=8                          ; [Principal] Cerrar la Ventana Flotante del FX n para las pistas seleccionadas
SWS_RESTLOOP=5                           ; [Principal] Restore loop selection, slot n
SWS_RESTTIME=5                           ; [Principal] Restore time selection, slot n
SWS_SAVELOOP=5                           ; [Principal] Save loop selection, slot n
SWS_SAVETIME=5                           ; [Principal] Save time selection, slot n
SWS_SEL=32                               ; [Principal] Select only track n
SWSSNAPSHOT_GET=12                       ; [Principal] Recuperar SnapShot n
SWSSNAPSHOT_SAVE=12                      ; [Principal] Save as snapshot n

[Notes]
Action_help_file="C:\Users\Ariel\AppData\Roaming\REAPER\S&M_Action_help_en.ini"
BigFontName=Arial
Lock=0
Type=0
WrapText=0

[ProjectTemplates]
Max_slot=0

[RegionPlaylist]
BigFontName=Arial
MonitorMode=0
Repeat=0
SeekImmediate=0
SeekPlay=0
ShufflePlaylist=0

[Resources]
AddMediaFileOptions=0
AutoFillDirColorThemes="C:\Users\Ariel\AppData\Roaming\REAPER\ColorThemes"
AutoFillDirFXChains="C:\Users\Ariel\AppData\Roaming\REAPER\FXChains"
AutoFillDirMediaFiles="C:\Users\Ariel\AppData\Roaming\REAPER\MediaFiles"
AutoFillDirProjectTemplates="C:\Users\Ariel\AppData\Roaming\REAPER\ProjectTemplates"
AutoFillDirTrack_icons="C:\Users\Ariel\AppData\Roaming\REAPER\Data\track_icons"
AutoFillDirTrackTemplates="C:\Users\Ariel\AppData\Roaming\REAPER\TrackTemplates"
AutoSaveDirFXChains="C:\Users\Ariel\AppData\Roaming\REAPER\FXChains"
AutoSaveDirMediaFiles="C:\Users\Ariel\AppData\Roaming\REAPER\MediaFiles"
AutoSaveDirProjectTemplates="C:\Users\Ariel\AppData\Roaming\REAPER\ProjectTemplates"
AutoSaveDirTrackTemplates="C:\Users\Ariel\AppData\Roaming\REAPER\TrackTemplates"
AutoSaveFXChain=0
AutoSaveFXChainName=0
AutoSaveTrTemplate=3
DblClickColorThemes=0
DblClickFXChains=0
DblClickMediaFiles=0
DblClickProjectTemplates=0
DblClickTrack_icons=0
DblClickTrackTemplates=0
Filter=1
SyncAutoDirsColorThemes=0
SyncAutoDirsFXChains=1
SyncAutoDirsMediaFiles=1
SyncAutoDirsProjectTemplates=1
SyncAutoDirsTrack_icons=0
SyncAutoDirsTrackTemplates=1
TiedActionsColorThemes=5
TiedActionsFXChains=0
TiedActionsMediaFiles=3
TiedActionsProjectTemplates=2
TiedActionsTrack_icons=4
TiedActionsTrackTemplates=1
Type=1

[Track_icons]
Max_slot=0

[TrackTemplates]
Max_slot=1
Slot1="MIDI.RTrackTemplate"

