#!/usr/bin/env bash
# This script aims to resolve `stow` conflicts whith existing files. It ask for package to sync, overrides the existing files in the $HOME directory whith the $HOME/.dotfiles ones, then adopt them again
set -euo pipefail

DOTFILES="$HOME/.dotfiles"
sync_package() {

    local source
    read -rp "Ruta de origen (relativa a $DOTFILES): " source

    if [[ ! -d "$DOTFILES/$source" ]]; then
        echo "La carpeta '$source' no existe."
        return 1
    fi

    rsync -aAXv "$DOTFILES/${source}/" "$HOME/"
    stow --adopt "$source"
}

sync_package
